### ISSUE TITLE
Lunches of Legends

### ISSUE THREAD

**Issue by RommelTJ** [RomzaLabs/Food#2]
**I'm submitting a ...**

- [x] meal plan request
- [x] grocery list request

## Notes:

Ok, we got breakfast downs. Now lunches. Any suggestions?

**Comment by RommelTJ** [comment]
I like basic sandwiches (bread/lettuce/mustard/protein) because they are easy to make in the morning. But if we want to meal prep on Sundays, perhaps we can choose something else. Can you meal prep sandwiches? Won't they get soggy? 

I found [this article](http://theeverygirl.com/20-lunches-you-can-meal-prep-on-sunday/) that has some good suggestions.

What do you think of the [Turkey Taco Lunch Bowls](https://sweetpeasandsaffron.com/turkey-taco-lunch-bowls-meal-prep/)?

**Comment by RommelTJ** [comment]
This belongs here: ![lunch time](https://i.imgur.com/7oKPqVp.gif)

https://i.imgur.com/7oKPqVp.gif

**Comment by leaningtower** [comment]
Yeah I like the turkey taco lunch bowls. Those look good and pretty easy to make but would we eat them cold? I don't like sandwiches because I prefer making meals ahead of time and just pulling them from the fridge. If the sandwich stuff is prepped though it's not a big deal for me to make them in the morning. Lol I like that gif.

**Comment by RommelTJ** [comment]
Hmm, good point about the cold. Why don't we try it cold? Or we can just remove the tomatoes or put them in a baggie? Let me know if I can close this issue. Sounds like we're settled.

**Comment by RommelTJ** [comment]
Closing.
